apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client-node-port
      image: duclu/multi-client
      ports:
        - containerPort: 3000
